# Generated by Django 2.1.7 on 2019-02-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_data', models.CharField(max_length=200)),
                ('ram_data', models.CharField(max_length=200)),
                ('hd_data', models.CharField(max_length=200)),
                ('netio_data', models.CharField(max_length=200)),
                ('netint_data', models.CharField(max_length=200)),
            ],
        ),
    ]
